# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CodeReviewer < Formula
  desc "AI-powered code review CLI for GitLab and GitHub. Uses Vertex AI (Gemini, Claude, Mistral) to analyze diffs and post actionable findings."
  homepage "https://github.com/OpticDiff/code-reviewer"
  version "0.22.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/OpticDiff/code-reviewer/releases/download/v0.22.0/code-reviewer_0.22.0_darwin_amd64.tar.gz"
      sha256 "d2e367467f635052dc6bb0cab57674cd1acbaeb4709184691f4d26dd6c3993d7"

      define_method(:install) do
        bin.install "code-reviewer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/OpticDiff/code-reviewer/releases/download/v0.22.0/code-reviewer_0.22.0_darwin_arm64.tar.gz"
      sha256 "08dcb4858b20e4708123c06f7ff15ca1e7cc8ddf598762c2b270b3bae2f50473"

      define_method(:install) do
        bin.install "code-reviewer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/OpticDiff/code-reviewer/releases/download/v0.22.0/code-reviewer_0.22.0_linux_amd64.tar.gz"
      sha256 "c3ab680a65429169faefd68a87dfa7c5db9f4d666093bed202335347a4e59926"
      define_method(:install) do
        bin.install "code-reviewer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/OpticDiff/code-reviewer/releases/download/v0.22.0/code-reviewer_0.22.0_linux_arm64.tar.gz"
      sha256 "10c66c8f6727a63b7e9dc9b95111a72a6017e7c6f2d2692a5b924c6e0cdc580c"
      define_method(:install) do
        bin.install "code-reviewer"
      end
    end
  end

  test do
    system "#{bin}/code-reviewer", "--version"
  end
end
